---
name: Lint

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6

      - name: Install linters
        run: |
          sudo apt-get update
          sudo apt-get install --yes shellcheck shfmt yamllint

      - name: Set up Just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0
        with:
          just-version: 1.55.1

      - name: Check Just syntax
        run: just check

      - name: Shellcheck
        run: just lint

      - name: YAML lint
        run: yamllint -c .yamllint.yml .github/workflows .github/ISSUE_TEMPLATE
